# Generated by Django 4.2.7 on 2023-11-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dateNews', '0002_alter_articles_options_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.CharField(max_length=3000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to='dateNews.articles'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='full_text',
            field=models.CharField(max_length=1000, verbose_name='Текст комментаряи'),
        ),
    ]
